### ISSUE TITLE
Required HTTP params on List RPCs

### ISSUE THREAD

**Issue by bndw** [CrowdStrike/perseus#164]
## Title

Request parameters appear to now be required for HTTP GET requests on the list RPCs.

## Version

https://github.com/CrowdStrike/perseus/commit/ca338172989550155e2c6a4155c25c975ef80b7d

## Description

The Connect API requires one or more request parameters to instantiate the request body on an HTTP GET. This is a change in behavior from the grpc-gateway implementation and breaks the embedded UI.

## Repro steps

Make a GET request to the ListModules or ListModuleVersions RPC without any query params. This causes a 400.
```
curl localhost:31138/api/v1/modules
{"code":3, "message":"unmarshal message: zero-length payload is not a valid JSON object", "details":[]}

curl localhost:31138/api/v1/module-versions
{"code":3, "message":"unmarshal message: zero-length payload is not a valid JSON object", "details":[]}
```

Adding one or more request params will allow the server to handle the request
```
curl localhost:31138/api/v1/modules\?page_size=10
{"modules":[...]}
```

Ideally we can modify the server to continue supporting zero query params on the GET requests. If not, we must update the UI to handle the breaking change.

**Comment by dylan-bourque** [comment]
Honestly, I think I would rather keep this new behavior but improve the error message.  Also, the equivalent CLI commands don't fail. 🤷

**Comment by dylan-bourque** [comment]
I spoke with the Buf devs and this is actually already fixed in `vanguard-go` but hasn't yet been released.  See [this issue](https://github.com/connectrpc/vanguard-go/issues/121).

**Comment by dylan-bourque** [comment]
This works again after updating `vanguard-go` to v0.2.0.

**Comment by dylan-bourque** [comment]
This works against after updating `vanguard-go` to v0.2.0.
